image:
  file: .gitpod.dockerfile

tasks:
  - init: pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - formulahendry.auto-close-tag
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter
    - ms-python.isort
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
